# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eM7KdVT8iVMk4riMYqz6_fFsuAwM5HKg
"""

def score_funct(tiger):
  score=0
  if tiger.scan_for_food()!=[]:
    score+=1000
  else:
    score+=10
  print(score)